name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          KEY: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd github-action-test
            git pull origin master
            cd demo
            chmod +x gradlew
            ./gradlew clean build
            cd build/libs
            nohup java -jar demo-0.0.1-SNAPSHOT.jar &
            exit

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: Set up JDK 11
#         uses: actions/setup-java@v2
#         with:
#           java-version: 11
#           distribution: "adopt"

#       - name: Validate Gradle wrapper
#         uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

#       - name: Grant execute permission for gradlew
#         run: |
#           cd demo
#           chmod +x gradlew

#       - name: Build with Gradle
#         run: |
#           cd demo
#           ./gradlew clean build
