name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the docker_compose
        run: docker-compose up -d --build

      - name: Buid the application
        run: docker-compose exec -T counter_app npm run build

  deploy:
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      # - name: Set up JDK 11
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: 11
      #     distribution: "adopt"

      # - name: Validate Gradle wrapper
      #   uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      # - name: Grant execute permission for gradlew
      #   run: |
      #     cd demo
      #     chmod +x gradlew

      # - name: Build with Gradle
      #   run: |
      #     cd demo
      #     ./gradlew clean build

      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USER_NAME  }}

        run: ssh -o StrictHostKeyChecking=no -i ${PRIVATE_KEY} ${USER_NAME}@${HOSTNAME}
